# Default values for cart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: default
image:
  repository: 655355946217.dkr.ecr.ap-southeast-1.amazonaws.com/retail-store-sample-app/cart
  tag:
resources:
  requests:
    cpu: 256m
    memory: 512Mi
  limits:
    cpu:
    memory: 512Mi
