---
# Source: retail-store-sample-orders-chart/templates/secret-db.yaml
apiVersion: v1
kind: Secret
metadata:
  name: orders-db
  namespace: {{ .Values.namespace }}
data:
  RETAIL_ORDERS_PERSISTENCE_USERNAME: "b3JkZXJz"
  RETAIL_ORDERS_PERSISTENCE_PASSWORD: "WGh5TW01UUo2ZUlWdW5Tdw=="